# Generated by Django 3.1.1 on 2020-10-10 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('remark', models.CharField(max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vandor_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('batch_sr_no', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
                ('vandor_price', models.IntegerField(default='0')),
                ('pack', models.IntegerField(default='0')),
                ('size', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default='0')),
                ('selling_price', models.IntegerField(default='0')),
                ('total', models.IntegerField(default='0')),
                ('date', models.DateField(auto_now_add=True)),
                ('paid', models.IntegerField(default='0')),
                ('remaining', models.IntegerField(default='0')),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='remainingstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_sr_no', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
                ('pack', models.IntegerField(default='0')),
                ('size', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default='0')),
                ('selling_price', models.IntegerField(default='0')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=256)),
                ('CustomerContact', models.CharField(max_length=256)),
                ('batch_no', models.CharField(max_length=256)),
                ('stock_name', models.CharField(max_length=256)),
                ('size', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default='0')),
                ('price', models.IntegerField(default='0')),
                ('paid', models.IntegerField(default='0')),
                ('remaining', models.IntegerField(default='0')),
                ('remark', models.CharField(max_length=100)),
                ('total', models.IntegerField(default='0')),
                ('option', models.CharField(max_length=50)),
                ('uploaded_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_sr_no', models.CharField(max_length=100)),
                ('stock_name', models.CharField(max_length=100)),
                ('vandor_price', models.IntegerField(default='0')),
                ('pack', models.IntegerField(default='0')),
                ('size', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default='0')),
                ('selling_price', models.IntegerField(default='0')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salehistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('remark', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.saletrans')),
            ],
        ),
        migrations.CreateModel(
            name='Purchasehistroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('remark', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.purchase')),
            ],
        ),
    ]
